#!/bin/bash

#Set the array of folders
DIRECTORIES=( directories go here );

#For each item in array, run the commands

for dir in ${DIRECTORIES[@]} ; do

  cd ${dir}/public_html;

  echo "";
  echo "";
  echo "*****************************************************" ;
  echo "UPDATING: " ${dir} " in " `pwd` ;
  echo "*****************************************************" ;
  echo "";
  echo "";

  wp theme update --all;
  wp plugin update --all;
  wp theme list;
  wp plugin list;
  wp core update;
  wp checksum core;
  wp db check;

  echo '';
  echo '';
  echo "*****************************************************" ;
  echo "UPDATE for ${dir} COMPLETE!" ;
  echo "*****************************************************" ;
  echo '';
  echo '';

  cd ../.. ;
done
